[project]
name = "database-engine-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyparsing>=3.3.2",
    "tabulate>=0.10.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.8",
    "pytest>=9.1.1",
]


[tool.pytest.ini_options]
pythonpath = "."
